apiVersion: v1
kind: Secret
metadata:
  name: telegram-bot-credentials
  labels:
    {{- include "my-bot-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  credentials.json: |
{{ .Values.bot.googleCredentials | indent 4 }}
