apiVersion: v1
kind: Secret
metadata:
  name: streetfood-bot-secrets
type: Opaque
stringData:
  TELEGRAM_TOKEN: "NEW_TOKEN_HERE"
  GOOGLE_CREDENTIALS: |
    {
      "type": "service_account",
      ...
    }
