{{- if .Values.bot }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-bot-chart.fullname" . }}
type: Opaque
stringData:
  {{- if .Values.bot.telegramToken }}
  TELEGRAM_TOKEN: {{ .Values.bot.telegramToken | quote }}
  {{- end }}
  {{- if .Values.bot.googleCredentials }}
  GOOGLE_CREDENTIALS: |
{{ .Values.bot.googleCredentials | indent 4 }}
  {{- end }}
{{- end }}
